version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - custom-network
  webserver:
    image: nginx
    container_name: nginx-webserver
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./Docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - custom-network
  database:
    image: postgres:latest
    container_name: pgsql-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - custom-network
  pga:
    image: dpage/pgadmin4:4.27
    container_name: pga
    tty: true
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dan@dan.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgdmin
    networks:
      - custom-network
volumes:
  pgsql-data:
  pgadmin-data:
networks:
  custom-network:
    driver: bridge